flysystem:
  storages:
    ftp.storage:
      adapter: 'ftp'
      options:
        host: '%env(resolve:FILESYS_HOST)%'
        username: '%env(resolve:FILESYS_USERNAME)%'
        password: '%env(resolve:FILESYS_PASSWORD)%'
        port: '%env(resolve:FILESYS_PORT)%'
        root: '%env(resolve:FILESYS_ROOT)%'
        passive: true
        ssl: true
        timeout: 30
        ignore_passive_address: ~
        utf8: false
    default.storage:
      adapter: 'local'
      options:
        directory: '%kernel.project_dir%/public'
